### ISSUE TITLE
Add audit validations to CircleCI

### ISSUE THREAD

**Issue by UX-Chris** [request-yo-racks/web#76] opened 2018-04-13 00:20 UTC
Issue Type
----------

- Feature request

Current Behavior
----------------

CircleCI does not run audit validations.

Expected Behavior
-----------------

CircleCI will run a Lighthouse audit and provide the score to ensure the application stays above acceptable standards.

Possible Solution
-----------------

Implement audit validations to CircleCI.

**Comment by rgreinho** [comment] 2018-11-04 20:58
Duplicate of #79.

**Closed by rgreinho** 2018-11-04 20:58 UTC
