### ISSUE TITLE
Implement Lighthouse Audits

### ISSUE THREAD

**Issue by UX-Chris** [request-yo-racks/web#75] opened 2018-04-13 00:05 UTC
Issue Type
----------

- Feature request

Current Behavior
----------------

The application has not been run through audits.

Expected Behavior
-----------------

Running lighthouse audits will report on how to improve the application.

Possible Solution
-----------------

Implement [Lighthouse audits](https://developers.google.com/web/tools/lighthouse/) to improve the performance and accessibility.

**Comment by rgreinho** [comment] 2018-04-13 14:55
Duplicate of #79.

**Closed by rgreinho** 2018-04-13 14:55 UTC
Labels: kind/duplicate, kind/enhancement, size/S, status/wontfix
